/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EndearingAppweb);
  }
}(this, function(expect, EndearingAppweb) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EndearingAppweb.CustomEntitiesApi();
  });

  describe('(package)', function() {
    describe('CustomEntitiesApi', function() {
      describe('apiCustomEntitiesGet', function() {
        it('should call apiCustomEntitiesGet successfully', function(done) {
          // TODO: uncomment apiCustomEntitiesGet call and complete the assertions
          /*

          instance.apiCustomEntitiesGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EndearingAppweb.CustomeEntityDTO);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiCustomEntitiesIdDelete', function() {
        it('should call apiCustomEntitiesIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiCustomEntitiesIdDelete call
          /*

          instance.apiCustomEntitiesIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiCustomEntitiesIdGet', function() {
        it('should call apiCustomEntitiesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiCustomEntitiesIdGet call and complete the assertions
          /*

          instance.apiCustomEntitiesIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EndearingAppweb.CustomeEntityDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiCustomEntitiesIdPut', function() {
        it('should call apiCustomEntitiesIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiCustomEntitiesIdPut call and complete the assertions
          /*
          var opts = {};

          instance.apiCustomEntitiesIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EndearingAppweb.CustomeEntityDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiCustomEntitiesPost', function() {
        it('should call apiCustomEntitiesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiCustomEntitiesPost call and complete the assertions
          /*
          var opts = {};

          instance.apiCustomEntitiesPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EndearingAppweb.CustomeEntityDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
