/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EndearingAppweb);
  }
}(this, function(expect, EndearingAppweb) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EndearingAppweb.OptionSetDefinitionsApi();
  });

  describe('(package)', function() {
    describe('OptionSetDefinitionsApi', function() {
      describe('apiOptionSetDefinitionsGet', function() {
        it('should call apiOptionSetDefinitionsGet successfully', function(done) {
          // TODO: uncomment apiOptionSetDefinitionsGet call and complete the assertions
          /*

          instance.apiOptionSetDefinitionsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EndearingAppweb.OptionSetDefinitionDTO);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiOptionSetDefinitionsIdDelete', function() {
        it('should call apiOptionSetDefinitionsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiOptionSetDefinitionsIdDelete call
          /*

          instance.apiOptionSetDefinitionsIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiOptionSetDefinitionsIdGet', function() {
        it('should call apiOptionSetDefinitionsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiOptionSetDefinitionsIdGet call and complete the assertions
          /*

          instance.apiOptionSetDefinitionsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EndearingAppweb.OptionSetDefinitionDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiOptionSetDefinitionsIdPut', function() {
        it('should call apiOptionSetDefinitionsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiOptionSetDefinitionsIdPut call and complete the assertions
          /*
          var opts = {};

          instance.apiOptionSetDefinitionsIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EndearingAppweb.OptionSetDefinitionDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiOptionSetDefinitionsPost', function() {
        it('should call apiOptionSetDefinitionsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiOptionSetDefinitionsPost call and complete the assertions
          /*
          var opts = {};

          instance.apiOptionSetDefinitionsPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EndearingAppweb.OptionSetDefinitionDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
