/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EndearingAppweb);
  }
}(this, function(expect, EndearingAppweb) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CustomAttributeData', function() {
      beforeEach(function() {
        instance = new EndearingAppweb.CustomAttributeData();
      });

      it('should create an instance of CustomAttributeData', function() {
        // TODO: update the code to test CustomAttributeData
        expect(instance).to.be.a(EndearingAppweb.CustomAttributeData);
      });

      it('should have the property attributeType (base name: "attributeType")', function() {
        // TODO: update the code to test the property attributeType
        expect(instance).to.have.property('attributeType');
        // expect(instance.attributeType).to.be(expectedValueLiteral);
      });

      it('should have the property constructor (base name: "constructor")', function() {
        // TODO: update the code to test the property constructor
        expect(instance).to.have.property('constructor');
        // expect(instance.constructor).to.be(expectedValueLiteral);
      });

      it('should have the property constructorArguments (base name: "constructorArguments")', function() {
        // TODO: update the code to test the property constructorArguments
        expect(instance).to.have.property('constructorArguments');
        // expect(instance.constructorArguments).to.be(expectedValueLiteral);
      });

      it('should have the property namedArguments (base name: "namedArguments")', function() {
        // TODO: update the code to test the property namedArguments
        expect(instance).to.have.property('namedArguments');
        // expect(instance.namedArguments).to.be(expectedValueLiteral);
      });

    });
  });

}));
