/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EndearingAppweb);
  }
}(this, function(expect, EndearingAppweb) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FieldDelta', function() {
      beforeEach(function() {
        instance = new EndearingAppweb.FieldDelta();
      });

      it('should create an instance of FieldDelta', function() {
        // TODO: update the code to test FieldDelta
        expect(instance).to.be.a(EndearingAppweb.FieldDelta);
      });

      it('should have the property kind (base name: "kind")', function() {
        // TODO: update the code to test the property kind
        expect(instance).to.have.property('kind');
        // expect(instance.kind).to.be(expectedValueLiteral);
      });

      it('should have the property structuredType (base name: "structuredType")', function() {
        // TODO: update the code to test the property structuredType
        expect(instance).to.have.property('structuredType');
        // expect(instance.structuredType).to.be(expectedValueLiteral);
      });

      it('should have the property expectedClrType (base name: "expectedClrType")', function() {
        // TODO: update the code to test the property expectedClrType
        expect(instance).to.have.property('expectedClrType');
        // expect(instance.expectedClrType).to.be(expectedValueLiteral);
      });

      it('should have the property updatableProperties (base name: "updatableProperties")', function() {
        // TODO: update the code to test the property updatableProperties
        expect(instance).to.have.property('updatableProperties');
        // expect(instance.updatableProperties).to.be(expectedValueLiteral);
      });

      it('should have the property isComplexType (base name: "isComplexType")', function() {
        // TODO: update the code to test the property isComplexType
        expect(instance).to.have.property('isComplexType');
        // expect(instance.isComplexType).to.be(expectedValueLiteral);
      });

    });
  });

}));
