/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EndearingAppweb);
  }
}(this, function(expect, EndearingAppweb) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IEdmVocabularyAnnotation', function() {
      beforeEach(function() {
        instance = new EndearingAppweb.IEdmVocabularyAnnotation();
      });

      it('should create an instance of IEdmVocabularyAnnotation', function() {
        // TODO: update the code to test IEdmVocabularyAnnotation
        expect(instance).to.be.a(EndearingAppweb.IEdmVocabularyAnnotation);
      });

      it('should have the property qualifier (base name: "qualifier")', function() {
        // TODO: update the code to test the property qualifier
        expect(instance).to.have.property('qualifier');
        // expect(instance.qualifier).to.be(expectedValueLiteral);
      });

      it('should have the property term (base name: "term")', function() {
        // TODO: update the code to test the property term
        expect(instance).to.have.property('term');
        // expect(instance.term).to.be(expectedValueLiteral);
      });

      it('should have the property target (base name: "target")', function() {
        // TODO: update the code to test the property target
        expect(instance).to.have.property('target');
        // expect(instance.target).to.be(expectedValueLiteral);
      });

      it('should have the property value (base name: "value")', function() {
        // TODO: update the code to test the property value
        expect(instance).to.have.property('value');
        // expect(instance.value).to.be(expectedValueLiteral);
      });

      it('should have the property usesDefault (base name: "usesDefault")', function() {
        // TODO: update the code to test the property usesDefault
        expect(instance).to.have.property('usesDefault');
        // expect(instance.usesDefault).to.be(expectedValueLiteral);
      });

    });
  });

}));
