/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EndearingAppweb);
  }
}(this, function(expect, EndearingAppweb) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ODataServiceDocument', function() {
      beforeEach(function() {
        instance = new EndearingAppweb.ODataServiceDocument();
      });

      it('should create an instance of ODataServiceDocument', function() {
        // TODO: update the code to test ODataServiceDocument
        expect(instance).to.be.a(EndearingAppweb.ODataServiceDocument);
      });

      it('should have the property typeAnnotation (base name: "typeAnnotation")', function() {
        // TODO: update the code to test the property typeAnnotation
        expect(instance).to.have.property('typeAnnotation');
        // expect(instance.typeAnnotation).to.be(expectedValueLiteral);
      });

      it('should have the property entitySets (base name: "entitySets")', function() {
        // TODO: update the code to test the property entitySets
        expect(instance).to.have.property('entitySets');
        // expect(instance.entitySets).to.be(expectedValueLiteral);
      });

      it('should have the property singletons (base name: "singletons")', function() {
        // TODO: update the code to test the property singletons
        expect(instance).to.have.property('singletons');
        // expect(instance.singletons).to.be(expectedValueLiteral);
      });

      it('should have the property functionImports (base name: "functionImports")', function() {
        // TODO: update the code to test the property functionImports
        expect(instance).to.have.property('functionImports');
        // expect(instance.functionImports).to.be(expectedValueLiteral);
      });

    });
  });

}));
