/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EndearingAppweb);
  }
}(this, function(expect, EndearingAppweb) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PropertyAttributes', function() {
      beforeEach(function() {
        instance = EndearingAppweb.PropertyAttributes;
      });

      it('should create an instance of PropertyAttributes', function() {
        // TODO: update the code to test PropertyAttributes
        expect(instance).to.be.a('object');
      });

      it('should have the property _0', function() {
        expect(instance).to.have.property('_0');
        expect(instance._0).to.be(0);
      });

      it('should have the property _512', function() {
        expect(instance).to.have.property('_512');
        expect(instance._512).to.be(512);
      });

      it('should have the property _1024', function() {
        expect(instance).to.have.property('_1024');
        expect(instance._1024).to.be(1024);
      });

      it('should have the property _4096', function() {
        expect(instance).to.have.property('_4096');
        expect(instance._4096).to.be(4096);
      });

      it('should have the property _8192', function() {
        expect(instance).to.have.property('_8192');
        expect(instance._8192).to.be(8192);
      });

      it('should have the property _16384', function() {
        expect(instance).to.have.property('_16384');
        expect(instance._16384).to.be(16384);
      });

      it('should have the property _32768', function() {
        expect(instance).to.have.property('_32768');
        expect(instance._32768).to.be(32768);
      });

      it('should have the property _62464', function() {
        expect(instance).to.have.property('_62464');
        expect(instance._62464).to.be(62464);
      });

    });
  });

}));
