/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EndearingAppweb);
  }
}(this, function(expect, EndearingAppweb) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RelationshipDTO', function() {
      beforeEach(function() {
        instance = new EndearingAppweb.RelationshipDTO();
      });

      it('should create an instance of RelationshipDTO', function() {
        // TODO: update the code to test RelationshipDTO
        expect(instance).to.be.a(EndearingAppweb.RelationshipDTO);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property sourceCustomEntityId (base name: "sourceCustomEntityId")', function() {
        // TODO: update the code to test the property sourceCustomEntityId
        expect(instance).to.have.property('sourceCustomEntityId');
        // expect(instance.sourceCustomEntityId).to.be(expectedValueLiteral);
      });

      it('should have the property sourceFieldId (base name: "sourceFieldId")', function() {
        // TODO: update the code to test the property sourceFieldId
        expect(instance).to.have.property('sourceFieldId');
        // expect(instance.sourceFieldId).to.be(expectedValueLiteral);
      });

      it('should have the property referencedFieldId (base name: "referencedFieldId")', function() {
        // TODO: update the code to test the property referencedFieldId
        expect(instance).to.have.property('referencedFieldId');
        // expect(instance.referencedFieldId).to.be(expectedValueLiteral);
      });

      it('should have the property referencedCustomEntityId (base name: "referencedCustomEntityId")', function() {
        // TODO: update the code to test the property referencedCustomEntityId
        expect(instance).to.have.property('referencedCustomEntityId');
        // expect(instance.referencedCustomEntityId).to.be(expectedValueLiteral);
      });

      it('should have the property constraintName (base name: "constraintName")', function() {
        // TODO: update the code to test the property constraintName
        expect(instance).to.have.property('constraintName');
        // expect(instance.constraintName).to.be(expectedValueLiteral);
      });

    });
  });

}));
