target: all

auth_enabled: false

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

schema_config:
  configs:
    - from: 2022-01-01 
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h