/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Type from './Type';

/**
 * The CustomAttributeTypedArgument model module.
 * @module model/CustomAttributeTypedArgument
 * @version 1.0
 */
export default class CustomAttributeTypedArgument {
  /**
   * Constructs a new <code>CustomAttributeTypedArgument</code>.
   * @alias module:model/CustomAttributeTypedArgument
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CustomAttributeTypedArgument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomAttributeTypedArgument} obj Optional instance to populate.
   * @return {module:model/CustomAttributeTypedArgument} The populated <code>CustomAttributeTypedArgument</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CustomAttributeTypedArgument();
      if (data.hasOwnProperty('argumentType'))
        obj.argumentType = Type.constructFromObject(data['argumentType']);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:model/Type} argumentType
 */
CustomAttributeTypedArgument.prototype.argumentType = undefined;

/**
 * @member {Object} value
 */
CustomAttributeTypedArgument.prototype.value = undefined;

