/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CustomAttributeTypedArgument from './CustomAttributeTypedArgument';
import MemberInfo from './MemberInfo';

/**
 * The CustomAttributeNamedArgument model module.
 * @module model/CustomAttributeNamedArgument
 * @version 1.0
 */
export default class CustomAttributeNamedArgument {
  /**
   * Constructs a new <code>CustomAttributeNamedArgument</code>.
   * @alias module:model/CustomAttributeNamedArgument
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CustomAttributeNamedArgument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomAttributeNamedArgument} obj Optional instance to populate.
   * @return {module:model/CustomAttributeNamedArgument} The populated <code>CustomAttributeNamedArgument</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CustomAttributeNamedArgument();
      if (data.hasOwnProperty('memberInfo'))
        obj.memberInfo = MemberInfo.constructFromObject(data['memberInfo']);
      if (data.hasOwnProperty('typedValue'))
        obj.typedValue = CustomAttributeTypedArgument.constructFromObject(data['typedValue']);
      if (data.hasOwnProperty('memberName'))
        obj.memberName = ApiClient.convertToType(data['memberName'], 'String');
      if (data.hasOwnProperty('isField'))
        obj.isField = ApiClient.convertToType(data['isField'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/MemberInfo} memberInfo
 */
CustomAttributeNamedArgument.prototype.memberInfo = undefined;

/**
 * @member {module:model/CustomAttributeTypedArgument} typedValue
 */
CustomAttributeNamedArgument.prototype.typedValue = undefined;

/**
 * @member {String} memberName
 */
CustomAttributeNamedArgument.prototype.memberName = undefined;

/**
 * @member {Boolean} isField
 */
CustomAttributeNamedArgument.prototype.isField = undefined;

