/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FieldDto model module.
 * @module model/FieldDto
 * @version 1.0
 */
export default class FieldDto {
  /**
   * Constructs a new <code>FieldDto</code>.
   * @alias module:model/FieldDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FieldDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FieldDto} obj Optional instance to populate.
   * @return {module:model/FieldDto} The populated <code>FieldDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FieldDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('customEntityId'))
        obj.customEntityId = ApiClient.convertToType(data['customEntityId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'Number');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'Number');
      if (data.hasOwnProperty('isPrimaryKey'))
        obj.isPrimaryKey = ApiClient.convertToType(data['isPrimaryKey'], 'Boolean');
      if (data.hasOwnProperty('isNullable'))
        obj.isNullable = ApiClient.convertToType(data['isNullable'], 'Boolean');
      if (data.hasOwnProperty('isSystemField'))
        obj.isSystemField = ApiClient.convertToType(data['isSystemField'], 'Boolean');
      if (data.hasOwnProperty('isIndexed'))
        obj.isIndexed = ApiClient.convertToType(data['isIndexed'], 'Boolean');
      if (data.hasOwnProperty('isUnique'))
        obj.isUnique = ApiClient.convertToType(data['isUnique'], 'Boolean');
      if (data.hasOwnProperty('isRequired'))
        obj.isRequired = ApiClient.convertToType(data['isRequired'], 'Boolean');
      if (data.hasOwnProperty('optionSetDefinitionId'))
        obj.optionSetDefinitionId = ApiClient.convertToType(data['optionSetDefinitionId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
FieldDto.prototype.id = undefined;

/**
 * @member {String} customEntityId
 */
FieldDto.prototype.customEntityId = undefined;

/**
 * @member {String} name
 */
FieldDto.prototype.name = undefined;

/**
 * @member {String} displayName
 */
FieldDto.prototype.displayName = undefined;

/**
 * @member {String} description
 */
FieldDto.prototype.description = undefined;

/**
 * @member {String} metadata
 */
FieldDto.prototype.metadata = undefined;

/**
 * @member {Number} type
 */
FieldDto.prototype.type = undefined;

/**
 * @member {Number} size
 */
FieldDto.prototype.size = undefined;

/**
 * @member {Boolean} isPrimaryKey
 */
FieldDto.prototype.isPrimaryKey = undefined;

/**
 * @member {Boolean} isNullable
 */
FieldDto.prototype.isNullable = undefined;

/**
 * @member {Boolean} isSystemField
 */
FieldDto.prototype.isSystemField = undefined;

/**
 * @member {Boolean} isIndexed
 */
FieldDto.prototype.isIndexed = undefined;

/**
 * @member {Boolean} isUnique
 */
FieldDto.prototype.isUnique = undefined;

/**
 * @member {Boolean} isRequired
 */
FieldDto.prototype.isRequired = undefined;

/**
 * @member {String} optionSetDefinitionId
 */
FieldDto.prototype.optionSetDefinitionId = undefined;

