/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DeltaItemKind from './DeltaItemKind';
import Type from './Type';

/**
 * The FieldDelta model module.
 * @module model/FieldDelta
 * @version 1.0
 */
export default class FieldDelta {
  /**
   * Constructs a new <code>FieldDelta</code>.
   * @alias module:model/FieldDelta
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FieldDelta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FieldDelta} obj Optional instance to populate.
   * @return {module:model/FieldDelta} The populated <code>FieldDelta</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FieldDelta();
      if (data.hasOwnProperty('kind'))
        obj.kind = DeltaItemKind.constructFromObject(data['kind']);
      if (data.hasOwnProperty('structuredType'))
        obj.structuredType = Type.constructFromObject(data['structuredType']);
      if (data.hasOwnProperty('expectedClrType'))
        obj.expectedClrType = Type.constructFromObject(data['expectedClrType']);
      if (data.hasOwnProperty('updatableProperties'))
        obj.updatableProperties = ApiClient.convertToType(data['updatableProperties'], ['String']);
      if (data.hasOwnProperty('isComplexType'))
        obj.isComplexType = ApiClient.convertToType(data['isComplexType'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/DeltaItemKind} kind
 */
FieldDelta.prototype.kind = undefined;

/**
 * @member {module:model/Type} structuredType
 */
FieldDelta.prototype.structuredType = undefined;

/**
 * @member {module:model/Type} expectedClrType
 */
FieldDelta.prototype.expectedClrType = undefined;

/**
 * @member {Array.<String>} updatableProperties
 */
FieldDelta.prototype.updatableProperties = undefined;

/**
 * @member {Boolean} isComplexType
 */
FieldDelta.prototype.isComplexType = undefined;

