/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class GenericParameterAttributes.
 * @enum {Number}
 * @readonly
 */
const GenericParameterAttributes = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 2
   * @const
   */
  _2: 2,

  /**
   * value: 3
   * @const
   */
  _3: 3,

  /**
   * value: 4
   * @const
   */
  _4: 4,

  /**
   * value: 8
   * @const
   */
  _8: 8,

  /**
   * value: 16
   * @const
   */
  _16: 16,

  /**
   * value: 28
   * @const
   */
  _28: 28,

  /**
   * Returns a <code>GenericParameterAttributes</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/GenericParameterAttributes} The enum <code>GenericParameterAttributes</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {GenericParameterAttributes};