/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import IEdmType from './IEdmType';

/**
 * The IEdmTypeReference model module.
 * @module model/IEdmTypeReference
 * @version 1.0
 */
export default class IEdmTypeReference {
  /**
   * Constructs a new <code>IEdmTypeReference</code>.
   * @alias module:model/IEdmTypeReference
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IEdmTypeReference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IEdmTypeReference} obj Optional instance to populate.
   * @return {module:model/IEdmTypeReference} The populated <code>IEdmTypeReference</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IEdmTypeReference();
      if (data.hasOwnProperty('isNullable'))
        obj.isNullable = ApiClient.convertToType(data['isNullable'], 'Boolean');
      if (data.hasOwnProperty('definition'))
        obj.definition = IEdmType.constructFromObject(data['definition']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} isNullable
 */
IEdmTypeReference.prototype.isNullable = undefined;

/**
 * @member {module:model/IEdmType} definition
 */
IEdmTypeReference.prototype.definition = undefined;

