/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import EdmSchemaElementKind from './EdmSchemaElementKind';
import IEdmEntityContainerElement from './IEdmEntityContainerElement';

/**
 * The IEdmEntityContainer model module.
 * @module model/IEdmEntityContainer
 * @version 1.0
 */
export default class IEdmEntityContainer {
  /**
   * Constructs a new <code>IEdmEntityContainer</code>.
   * @alias module:model/IEdmEntityContainer
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IEdmEntityContainer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IEdmEntityContainer} obj Optional instance to populate.
   * @return {module:model/IEdmEntityContainer} The populated <code>IEdmEntityContainer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IEdmEntityContainer();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('schemaElementKind'))
        obj.schemaElementKind = EdmSchemaElementKind.constructFromObject(data['schemaElementKind']);
      if (data.hasOwnProperty('namespace'))
        obj.namespace = ApiClient.convertToType(data['namespace'], 'String');
      if (data.hasOwnProperty('elements'))
        obj.elements = ApiClient.convertToType(data['elements'], [IEdmEntityContainerElement]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
IEdmEntityContainer.prototype.name = undefined;

/**
 * @member {module:model/EdmSchemaElementKind} schemaElementKind
 */
IEdmEntityContainer.prototype.schemaElementKind = undefined;

/**
 * @member {String} namespace
 */
IEdmEntityContainer.prototype.namespace = undefined;

/**
 * @member {Array.<module:model/IEdmEntityContainerElement>} elements
 */
IEdmEntityContainer.prototype.elements = undefined;

