/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import EdmContainerElementKind from './EdmContainerElementKind';
import IEdmEntityContainer from './IEdmEntityContainer';

/**
 * The IEdmEntityContainerElement model module.
 * @module model/IEdmEntityContainerElement
 * @version 1.0
 */
export default class IEdmEntityContainerElement {
  /**
   * Constructs a new <code>IEdmEntityContainerElement</code>.
   * @alias module:model/IEdmEntityContainerElement
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IEdmEntityContainerElement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IEdmEntityContainerElement} obj Optional instance to populate.
   * @return {module:model/IEdmEntityContainerElement} The populated <code>IEdmEntityContainerElement</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IEdmEntityContainerElement();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('containerElementKind'))
        obj.containerElementKind = EdmContainerElementKind.constructFromObject(data['containerElementKind']);
      if (data.hasOwnProperty('container'))
        obj.container = IEdmEntityContainer.constructFromObject(data['container']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
IEdmEntityContainerElement.prototype.name = undefined;

/**
 * @member {module:model/EdmContainerElementKind} containerElementKind
 */
IEdmEntityContainerElement.prototype.containerElementKind = undefined;

/**
 * @member {module:model/IEdmEntityContainer} container
 */
IEdmEntityContainerElement.prototype.container = undefined;

