/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import EdmExpressionKind from './EdmExpressionKind';

/**
 * The IEdmExpression model module.
 * @module model/IEdmExpression
 * @version 1.0
 */
export default class IEdmExpression {
  /**
   * Constructs a new <code>IEdmExpression</code>.
   * @alias module:model/IEdmExpression
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IEdmExpression</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IEdmExpression} obj Optional instance to populate.
   * @return {module:model/IEdmExpression} The populated <code>IEdmExpression</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IEdmExpression();
      if (data.hasOwnProperty('expressionKind'))
        obj.expressionKind = EdmExpressionKind.constructFromObject(data['expressionKind']);
    }
    return obj;
  }
}

/**
 * @member {module:model/EdmExpressionKind} expressionKind
 */
IEdmExpression.prototype.expressionKind = undefined;

