/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import EdmTypeKind from './EdmTypeKind';

/**
 * The IEdmType model module.
 * @module model/IEdmType
 * @version 1.0
 */
export default class IEdmType {
  /**
   * Constructs a new <code>IEdmType</code>.
   * @alias module:model/IEdmType
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IEdmType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IEdmType} obj Optional instance to populate.
   * @return {module:model/IEdmType} The populated <code>IEdmType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IEdmType();
      if (data.hasOwnProperty('typeKind'))
        obj.typeKind = EdmTypeKind.constructFromObject(data['typeKind']);
    }
    return obj;
  }
}

/**
 * @member {module:model/EdmTypeKind} typeKind
 */
IEdmType.prototype.typeKind = undefined;

