/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class MemberTypes.
 * @enum {Number}
 * @readonly
 */
const MemberTypes = {
  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 2
   * @const
   */
  _2: 2,

  /**
   * value: 4
   * @const
   */
  _4: 4,

  /**
   * value: 8
   * @const
   */
  _8: 8,

  /**
   * value: 16
   * @const
   */
  _16: 16,

  /**
   * value: 32
   * @const
   */
  _32: 32,

  /**
   * value: 64
   * @const
   */
  _64: 64,

  /**
   * value: 128
   * @const
   */
  _128: 128,

  /**
   * value: 191
   * @const
   */
  _191: 191,

  /**
   * Returns a <code>MemberTypes</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/MemberTypes} The enum <code>MemberTypes</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {MemberTypes};