/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class MethodAttributes.
 * @enum {Number}
 * @readonly
 */
const MethodAttributes = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 2
   * @const
   */
  _2: 2,

  /**
   * value: 3
   * @const
   */
  _3: 3,

  /**
   * value: 4
   * @const
   */
  _4: 4,

  /**
   * value: 5
   * @const
   */
  _5: 5,

  /**
   * value: 6
   * @const
   */
  _6: 6,

  /**
   * value: 7
   * @const
   */
  _7: 7,

  /**
   * value: 8
   * @const
   */
  _8: 8,

  /**
   * value: 16
   * @const
   */
  _16: 16,

  /**
   * value: 32
   * @const
   */
  _32: 32,

  /**
   * value: 64
   * @const
   */
  _64: 64,

  /**
   * value: 128
   * @const
   */
  _128: 128,

  /**
   * value: 256
   * @const
   */
  _256: 256,

  /**
   * value: 512
   * @const
   */
  _512: 512,

  /**
   * value: 1024
   * @const
   */
  _1024: 1024,

  /**
   * value: 2048
   * @const
   */
  _2048: 2048,

  /**
   * value: 4096
   * @const
   */
  _4096: 4096,

  /**
   * value: 8192
   * @const
   */
  _8192: 8192,

  /**
   * value: 16384
   * @const
   */
  _16384: 16384,

  /**
   * value: 32768
   * @const
   */
  _32768: 32768,

  /**
   * value: 53248
   * @const
   */
  _53248: 53248,

  /**
   * Returns a <code>MethodAttributes</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/MethodAttributes} The enum <code>MethodAttributes</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {MethodAttributes};