/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ODataTypeAnnotation from './ODataTypeAnnotation';

/**
 * The ODataSingletonInfo model module.
 * @module model/ODataSingletonInfo
 * @version 1.0
 */
export default class ODataSingletonInfo {
  /**
   * Constructs a new <code>ODataSingletonInfo</code>.
   * @alias module:model/ODataSingletonInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ODataSingletonInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ODataSingletonInfo} obj Optional instance to populate.
   * @return {module:model/ODataSingletonInfo} The populated <code>ODataSingletonInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ODataSingletonInfo();
      if (data.hasOwnProperty('typeAnnotation'))
        obj.typeAnnotation = ODataTypeAnnotation.constructFromObject(data['typeAnnotation']);
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/ODataTypeAnnotation} typeAnnotation
 */
ODataSingletonInfo.prototype.typeAnnotation = undefined;

/**
 * @member {String} url
 */
ODataSingletonInfo.prototype.url = undefined;

/**
 * @member {String} name
 */
ODataSingletonInfo.prototype.name = undefined;

/**
 * @member {String} title
 */
ODataSingletonInfo.prototype.title = undefined;

