/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ODataTypeAnnotation model module.
 * @module model/ODataTypeAnnotation
 * @version 1.0
 */
export default class ODataTypeAnnotation {
  /**
   * Constructs a new <code>ODataTypeAnnotation</code>.
   * @alias module:model/ODataTypeAnnotation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ODataTypeAnnotation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ODataTypeAnnotation} obj Optional instance to populate.
   * @return {module:model/ODataTypeAnnotation} The populated <code>ODataTypeAnnotation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ODataTypeAnnotation();
      if (data.hasOwnProperty('typeName'))
        obj.typeName = ApiClient.convertToType(data['typeName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} typeName
 */
ODataTypeAnnotation.prototype.typeName = undefined;

