/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ODataEntitySetInfo from './ODataEntitySetInfo';
import ODataFunctionImportInfo from './ODataFunctionImportInfo';
import ODataSingletonInfo from './ODataSingletonInfo';
import ODataTypeAnnotation from './ODataTypeAnnotation';

/**
 * The ODataServiceDocument model module.
 * @module model/ODataServiceDocument
 * @version 1.0
 */
export default class ODataServiceDocument {
  /**
   * Constructs a new <code>ODataServiceDocument</code>.
   * @alias module:model/ODataServiceDocument
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ODataServiceDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ODataServiceDocument} obj Optional instance to populate.
   * @return {module:model/ODataServiceDocument} The populated <code>ODataServiceDocument</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ODataServiceDocument();
      if (data.hasOwnProperty('typeAnnotation'))
        obj.typeAnnotation = ODataTypeAnnotation.constructFromObject(data['typeAnnotation']);
      if (data.hasOwnProperty('entitySets'))
        obj.entitySets = ApiClient.convertToType(data['entitySets'], [ODataEntitySetInfo]);
      if (data.hasOwnProperty('singletons'))
        obj.singletons = ApiClient.convertToType(data['singletons'], [ODataSingletonInfo]);
      if (data.hasOwnProperty('functionImports'))
        obj.functionImports = ApiClient.convertToType(data['functionImports'], [ODataFunctionImportInfo]);
    }
    return obj;
  }
}

/**
 * @member {module:model/ODataTypeAnnotation} typeAnnotation
 */
ODataServiceDocument.prototype.typeAnnotation = undefined;

/**
 * @member {Array.<module:model/ODataEntitySetInfo>} entitySets
 */
ODataServiceDocument.prototype.entitySets = undefined;

/**
 * @member {Array.<module:model/ODataSingletonInfo>} singletons
 */
ODataServiceDocument.prototype.singletons = undefined;

/**
 * @member {Array.<module:model/ODataFunctionImportInfo>} functionImports
 */
ODataServiceDocument.prototype.functionImports = undefined;

