/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OptionSetDefinitionDTO model module.
 * @module model/OptionSetDefinitionDTO
 * @version 1.0
 */
export default class OptionSetDefinitionDTO {
  /**
   * Constructs a new <code>OptionSetDefinitionDTO</code>.
   * @alias module:model/OptionSetDefinitionDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OptionSetDefinitionDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OptionSetDefinitionDTO} obj Optional instance to populate.
   * @return {module:model/OptionSetDefinitionDTO} The populated <code>OptionSetDefinitionDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OptionSetDefinitionDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('isGlobal'))
        obj.isGlobal = ApiClient.convertToType(data['isGlobal'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
OptionSetDefinitionDTO.prototype.id = undefined;

/**
 * @member {String} name
 */
OptionSetDefinitionDTO.prototype.name = undefined;

/**
 * @member {Boolean} isGlobal
 */
OptionSetDefinitionDTO.prototype.isGlobal = undefined;

