/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OptionDTO model module.
 * @module model/OptionDTO
 * @version 1.0
 */
export default class OptionDTO {
  /**
   * Constructs a new <code>OptionDTO</code>.
   * @alias module:model/OptionDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OptionDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OptionDTO} obj Optional instance to populate.
   * @return {module:model/OptionDTO} The populated <code>OptionDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OptionDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
OptionDTO.prototype.id = undefined;

/**
 * @member {Number} value
 */
OptionDTO.prototype.value = undefined;

/**
 * @member {String} displayName
 */
OptionDTO.prototype.displayName = undefined;

/**
 * @member {String} name
 */
OptionDTO.prototype.name = undefined;

/**
 * @member {String} description
 */
OptionDTO.prototype.description = undefined;

