/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RelationshipDTO model module.
 * @module model/RelationshipDTO
 * @version 1.0
 */
export default class RelationshipDTO {
  /**
   * Constructs a new <code>RelationshipDTO</code>.
   * @alias module:model/RelationshipDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RelationshipDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RelationshipDTO} obj Optional instance to populate.
   * @return {module:model/RelationshipDTO} The populated <code>RelationshipDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RelationshipDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('sourceCustomEntityId'))
        obj.sourceCustomEntityId = ApiClient.convertToType(data['sourceCustomEntityId'], 'String');
      if (data.hasOwnProperty('sourceFieldId'))
        obj.sourceFieldId = ApiClient.convertToType(data['sourceFieldId'], 'String');
      if (data.hasOwnProperty('referencedFieldId'))
        obj.referencedFieldId = ApiClient.convertToType(data['referencedFieldId'], 'String');
      if (data.hasOwnProperty('referencedCustomEntityId'))
        obj.referencedCustomEntityId = ApiClient.convertToType(data['referencedCustomEntityId'], 'String');
      if (data.hasOwnProperty('constraintName'))
        obj.constraintName = ApiClient.convertToType(data['constraintName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
RelationshipDTO.prototype.id = undefined;

/**
 * @member {String} sourceCustomEntityId
 */
RelationshipDTO.prototype.sourceCustomEntityId = undefined;

/**
 * @member {String} sourceFieldId
 */
RelationshipDTO.prototype.sourceFieldId = undefined;

/**
 * @member {String} referencedFieldId
 */
RelationshipDTO.prototype.referencedFieldId = undefined;

/**
 * @member {String} referencedCustomEntityId
 */
RelationshipDTO.prototype.referencedCustomEntityId = undefined;

/**
 * @member {String} constraintName
 */
RelationshipDTO.prototype.constraintName = undefined;

