/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import RelationshipDTO from './RelationshipDTO';
import ResultStatus from './ResultStatus';
import ValidationError from './ValidationError';

/**
 * The RelationshipDTOResult model module.
 * @module model/RelationshipDTOResult
 * @version 1.0
 */
export default class RelationshipDTOResult {
  /**
   * Constructs a new <code>RelationshipDTOResult</code>.
   * @alias module:model/RelationshipDTOResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RelationshipDTOResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RelationshipDTOResult} obj Optional instance to populate.
   * @return {module:model/RelationshipDTOResult} The populated <code>RelationshipDTOResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RelationshipDTOResult();
      if (data.hasOwnProperty('value'))
        obj.value = RelationshipDTO.constructFromObject(data['value']);
      if (data.hasOwnProperty('status'))
        obj.status = ResultStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('isSuccess'))
        obj.isSuccess = ApiClient.convertToType(data['isSuccess'], 'Boolean');
      if (data.hasOwnProperty('successMessage'))
        obj.successMessage = ApiClient.convertToType(data['successMessage'], 'String');
      if (data.hasOwnProperty('correlationId'))
        obj.correlationId = ApiClient.convertToType(data['correlationId'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('errors'))
        obj.errors = ApiClient.convertToType(data['errors'], ['String']);
      if (data.hasOwnProperty('validationErrors'))
        obj.validationErrors = ApiClient.convertToType(data['validationErrors'], [ValidationError]);
    }
    return obj;
  }
}

/**
 * @member {module:model/RelationshipDTO} value
 */
RelationshipDTOResult.prototype.value = undefined;

/**
 * @member {module:model/ResultStatus} status
 */
RelationshipDTOResult.prototype.status = undefined;

/**
 * @member {Boolean} isSuccess
 */
RelationshipDTOResult.prototype.isSuccess = undefined;

/**
 * @member {String} successMessage
 */
RelationshipDTOResult.prototype.successMessage = undefined;

/**
 * @member {String} correlationId
 */
RelationshipDTOResult.prototype.correlationId = undefined;

/**
 * @member {String} location
 */
RelationshipDTOResult.prototype.location = undefined;

/**
 * @member {Array.<String>} errors
 */
RelationshipDTOResult.prototype.errors = undefined;

/**
 * @member {Array.<module:model/ValidationError>} validationErrors
 */
RelationshipDTOResult.prototype.validationErrors = undefined;

