/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class ResultStatus.
 * @enum {Number}
 * @readonly
 */
const ResultStatus = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 2
   * @const
   */
  _2: 2,

  /**
   * value: 3
   * @const
   */
  _3: 3,

  /**
   * value: 4
   * @const
   */
  _4: 4,

  /**
   * value: 5
   * @const
   */
  _5: 5,

  /**
   * value: 6
   * @const
   */
  _6: 6,

  /**
   * value: 7
   * @const
   */
  _7: 7,

  /**
   * value: 8
   * @const
   */
  _8: 8,

  /**
   * value: 9
   * @const
   */
  _9: 9,

  /**
   * value: 10
   * @const
   */
  _10: 10,

  /**
   * Returns a <code>ResultStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ResultStatus} The enum <code>ResultStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {ResultStatus};