/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class TypeAttributes.
 * @enum {Number}
 * @readonly
 */
const TypeAttributes = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 2
   * @const
   */
  _2: 2,

  /**
   * value: 3
   * @const
   */
  _3: 3,

  /**
   * value: 4
   * @const
   */
  _4: 4,

  /**
   * value: 5
   * @const
   */
  _5: 5,

  /**
   * value: 6
   * @const
   */
  _6: 6,

  /**
   * value: 7
   * @const
   */
  _7: 7,

  /**
   * value: 8
   * @const
   */
  _8: 8,

  /**
   * value: 16
   * @const
   */
  _16: 16,

  /**
   * value: 24
   * @const
   */
  _24: 24,

  /**
   * value: 32
   * @const
   */
  _32: 32,

  /**
   * value: 128
   * @const
   */
  _128: 128,

  /**
   * value: 256
   * @const
   */
  _256: 256,

  /**
   * value: 1024
   * @const
   */
  _1024: 1024,

  /**
   * value: 2048
   * @const
   */
  _2048: 2048,

  /**
   * value: 4096
   * @const
   */
  _4096: 4096,

  /**
   * value: 8192
   * @const
   */
  _8192: 8192,

  /**
   * value: 16384
   * @const
   */
  _16384: 16384,

  /**
   * value: 65536
   * @const
   */
  _65536: 65536,

  /**
   * value: 131072
   * @const
   */
  _131072: 131072,

  /**
   * value: 196608
   * @const
   */
  _196608: 196608,

  /**
   * value: 262144
   * @const
   */
  _262144: 262144,

  /**
   * value: 264192
   * @const
   */
  _264192: 264192,

  /**
   * value: 1048576
   * @const
   */
  _1048576: 1048576,

  /**
   * value: 12582912
   * @const
   */
  _12582912: 12582912,

  /**
   * Returns a <code>TypeAttributes</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/TypeAttributes} The enum <code>TypeAttributes</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {TypeAttributes};