/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Assembly from './Assembly';
import ConstructorInfo from './ConstructorInfo';
import CustomAttributeData from './CustomAttributeData';
import GenericParameterAttributes from './GenericParameterAttributes';
import MemberTypes from './MemberTypes';
import MethodBase from './MethodBase';
import Module from './Module';
import RuntimeTypeHandle from './RuntimeTypeHandle';
import StructLayoutAttribute from './StructLayoutAttribute';
import TypeAttributes from './TypeAttributes';

/**
 * The Type model module.
 * @module model/Type
 * @version 1.0
 */
export default class Type {
  /**
   * Constructs a new <code>Type</code>.
   * @alias module:model/Type
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Type</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Type} obj Optional instance to populate.
   * @return {module:model/Type} The populated <code>Type</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Type();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('customAttributes'))
        obj.customAttributes = ApiClient.convertToType(data['customAttributes'], [CustomAttributeData]);
      if (data.hasOwnProperty('isCollectible'))
        obj.isCollectible = ApiClient.convertToType(data['isCollectible'], 'Boolean');
      if (data.hasOwnProperty('metadataToken'))
        obj.metadataToken = ApiClient.convertToType(data['metadataToken'], 'Number');
      if (data.hasOwnProperty('isInterface'))
        obj.isInterface = ApiClient.convertToType(data['isInterface'], 'Boolean');
      if (data.hasOwnProperty('memberType'))
        obj.memberType = MemberTypes.constructFromObject(data['memberType']);
      if (data.hasOwnProperty('namespace'))
        obj.namespace = ApiClient.convertToType(data['namespace'], 'String');
      if (data.hasOwnProperty('assemblyQualifiedName'))
        obj.assemblyQualifiedName = ApiClient.convertToType(data['assemblyQualifiedName'], 'String');
      if (data.hasOwnProperty('fullName'))
        obj.fullName = ApiClient.convertToType(data['fullName'], 'String');
      if (data.hasOwnProperty('assembly'))
        obj.assembly = Assembly.constructFromObject(data['assembly']);
      if (data.hasOwnProperty('module'))
        obj.module = Module.constructFromObject(data['module']);
      if (data.hasOwnProperty('isNested'))
        obj.isNested = ApiClient.convertToType(data['isNested'], 'Boolean');
      if (data.hasOwnProperty('declaringType'))
        obj.declaringType = Type.constructFromObject(data['declaringType']);
      if (data.hasOwnProperty('declaringMethod'))
        obj.declaringMethod = MethodBase.constructFromObject(data['declaringMethod']);
      if (data.hasOwnProperty('reflectedType'))
        obj.reflectedType = Type.constructFromObject(data['reflectedType']);
      if (data.hasOwnProperty('underlyingSystemType'))
        obj.underlyingSystemType = Type.constructFromObject(data['underlyingSystemType']);
      if (data.hasOwnProperty('isTypeDefinition'))
        obj.isTypeDefinition = ApiClient.convertToType(data['isTypeDefinition'], 'Boolean');
      if (data.hasOwnProperty('isArray'))
        obj.isArray = ApiClient.convertToType(data['isArray'], 'Boolean');
      if (data.hasOwnProperty('isByRef'))
        obj.isByRef = ApiClient.convertToType(data['isByRef'], 'Boolean');
      if (data.hasOwnProperty('isPointer'))
        obj.isPointer = ApiClient.convertToType(data['isPointer'], 'Boolean');
      if (data.hasOwnProperty('isConstructedGenericType'))
        obj.isConstructedGenericType = ApiClient.convertToType(data['isConstructedGenericType'], 'Boolean');
      if (data.hasOwnProperty('isGenericParameter'))
        obj.isGenericParameter = ApiClient.convertToType(data['isGenericParameter'], 'Boolean');
      if (data.hasOwnProperty('isGenericTypeParameter'))
        obj.isGenericTypeParameter = ApiClient.convertToType(data['isGenericTypeParameter'], 'Boolean');
      if (data.hasOwnProperty('isGenericMethodParameter'))
        obj.isGenericMethodParameter = ApiClient.convertToType(data['isGenericMethodParameter'], 'Boolean');
      if (data.hasOwnProperty('isGenericType'))
        obj.isGenericType = ApiClient.convertToType(data['isGenericType'], 'Boolean');
      if (data.hasOwnProperty('isGenericTypeDefinition'))
        obj.isGenericTypeDefinition = ApiClient.convertToType(data['isGenericTypeDefinition'], 'Boolean');
      if (data.hasOwnProperty('isSZArray'))
        obj.isSZArray = ApiClient.convertToType(data['isSZArray'], 'Boolean');
      if (data.hasOwnProperty('isVariableBoundArray'))
        obj.isVariableBoundArray = ApiClient.convertToType(data['isVariableBoundArray'], 'Boolean');
      if (data.hasOwnProperty('isByRefLike'))
        obj.isByRefLike = ApiClient.convertToType(data['isByRefLike'], 'Boolean');
      if (data.hasOwnProperty('isFunctionPointer'))
        obj.isFunctionPointer = ApiClient.convertToType(data['isFunctionPointer'], 'Boolean');
      if (data.hasOwnProperty('isUnmanagedFunctionPointer'))
        obj.isUnmanagedFunctionPointer = ApiClient.convertToType(data['isUnmanagedFunctionPointer'], 'Boolean');
      if (data.hasOwnProperty('hasElementType'))
        obj.hasElementType = ApiClient.convertToType(data['hasElementType'], 'Boolean');
      if (data.hasOwnProperty('genericTypeArguments'))
        obj.genericTypeArguments = ApiClient.convertToType(data['genericTypeArguments'], [Type]);
      if (data.hasOwnProperty('genericParameterPosition'))
        obj.genericParameterPosition = ApiClient.convertToType(data['genericParameterPosition'], 'Number');
      if (data.hasOwnProperty('genericParameterAttributes'))
        obj.genericParameterAttributes = GenericParameterAttributes.constructFromObject(data['genericParameterAttributes']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = TypeAttributes.constructFromObject(data['attributes']);
      if (data.hasOwnProperty('isAbstract'))
        obj.isAbstract = ApiClient.convertToType(data['isAbstract'], 'Boolean');
      if (data.hasOwnProperty('isImport'))
        obj.isImport = ApiClient.convertToType(data['isImport'], 'Boolean');
      if (data.hasOwnProperty('isSealed'))
        obj.isSealed = ApiClient.convertToType(data['isSealed'], 'Boolean');
      if (data.hasOwnProperty('isSpecialName'))
        obj.isSpecialName = ApiClient.convertToType(data['isSpecialName'], 'Boolean');
      if (data.hasOwnProperty('isClass'))
        obj.isClass = ApiClient.convertToType(data['isClass'], 'Boolean');
      if (data.hasOwnProperty('isNestedAssembly'))
        obj.isNestedAssembly = ApiClient.convertToType(data['isNestedAssembly'], 'Boolean');
      if (data.hasOwnProperty('isNestedFamANDAssem'))
        obj.isNestedFamANDAssem = ApiClient.convertToType(data['isNestedFamANDAssem'], 'Boolean');
      if (data.hasOwnProperty('isNestedFamily'))
        obj.isNestedFamily = ApiClient.convertToType(data['isNestedFamily'], 'Boolean');
      if (data.hasOwnProperty('isNestedFamORAssem'))
        obj.isNestedFamORAssem = ApiClient.convertToType(data['isNestedFamORAssem'], 'Boolean');
      if (data.hasOwnProperty('isNestedPrivate'))
        obj.isNestedPrivate = ApiClient.convertToType(data['isNestedPrivate'], 'Boolean');
      if (data.hasOwnProperty('isNestedPublic'))
        obj.isNestedPublic = ApiClient.convertToType(data['isNestedPublic'], 'Boolean');
      if (data.hasOwnProperty('isNotPublic'))
        obj.isNotPublic = ApiClient.convertToType(data['isNotPublic'], 'Boolean');
      if (data.hasOwnProperty('isPublic'))
        obj.isPublic = ApiClient.convertToType(data['isPublic'], 'Boolean');
      if (data.hasOwnProperty('isAutoLayout'))
        obj.isAutoLayout = ApiClient.convertToType(data['isAutoLayout'], 'Boolean');
      if (data.hasOwnProperty('isExplicitLayout'))
        obj.isExplicitLayout = ApiClient.convertToType(data['isExplicitLayout'], 'Boolean');
      if (data.hasOwnProperty('isLayoutSequential'))
        obj.isLayoutSequential = ApiClient.convertToType(data['isLayoutSequential'], 'Boolean');
      if (data.hasOwnProperty('isAnsiClass'))
        obj.isAnsiClass = ApiClient.convertToType(data['isAnsiClass'], 'Boolean');
      if (data.hasOwnProperty('isAutoClass'))
        obj.isAutoClass = ApiClient.convertToType(data['isAutoClass'], 'Boolean');
      if (data.hasOwnProperty('isUnicodeClass'))
        obj.isUnicodeClass = ApiClient.convertToType(data['isUnicodeClass'], 'Boolean');
      if (data.hasOwnProperty('isCOMObject'))
        obj.isCOMObject = ApiClient.convertToType(data['isCOMObject'], 'Boolean');
      if (data.hasOwnProperty('isContextful'))
        obj.isContextful = ApiClient.convertToType(data['isContextful'], 'Boolean');
      if (data.hasOwnProperty('isEnum'))
        obj.isEnum = ApiClient.convertToType(data['isEnum'], 'Boolean');
      if (data.hasOwnProperty('isMarshalByRef'))
        obj.isMarshalByRef = ApiClient.convertToType(data['isMarshalByRef'], 'Boolean');
      if (data.hasOwnProperty('isPrimitive'))
        obj.isPrimitive = ApiClient.convertToType(data['isPrimitive'], 'Boolean');
      if (data.hasOwnProperty('isValueType'))
        obj.isValueType = ApiClient.convertToType(data['isValueType'], 'Boolean');
      if (data.hasOwnProperty('isSignatureType'))
        obj.isSignatureType = ApiClient.convertToType(data['isSignatureType'], 'Boolean');
      if (data.hasOwnProperty('isSecurityCritical'))
        obj.isSecurityCritical = ApiClient.convertToType(data['isSecurityCritical'], 'Boolean');
      if (data.hasOwnProperty('isSecuritySafeCritical'))
        obj.isSecuritySafeCritical = ApiClient.convertToType(data['isSecuritySafeCritical'], 'Boolean');
      if (data.hasOwnProperty('isSecurityTransparent'))
        obj.isSecurityTransparent = ApiClient.convertToType(data['isSecurityTransparent'], 'Boolean');
      if (data.hasOwnProperty('structLayoutAttribute'))
        obj.structLayoutAttribute = StructLayoutAttribute.constructFromObject(data['structLayoutAttribute']);
      if (data.hasOwnProperty('typeInitializer'))
        obj.typeInitializer = ConstructorInfo.constructFromObject(data['typeInitializer']);
      if (data.hasOwnProperty('typeHandle'))
        obj.typeHandle = RuntimeTypeHandle.constructFromObject(data['typeHandle']);
      if (data.hasOwnProperty('guid'))
        obj.guid = ApiClient.convertToType(data['guid'], 'String');
      if (data.hasOwnProperty('baseType'))
        obj.baseType = Type.constructFromObject(data['baseType']);
      if (data.hasOwnProperty('isSerializable'))
        obj.isSerializable = ApiClient.convertToType(data['isSerializable'], 'Boolean');
      if (data.hasOwnProperty('containsGenericParameters'))
        obj.containsGenericParameters = ApiClient.convertToType(data['containsGenericParameters'], 'Boolean');
      if (data.hasOwnProperty('isVisible'))
        obj.isVisible = ApiClient.convertToType(data['isVisible'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Type.prototype.name = undefined;

/**
 * @member {Array.<module:model/CustomAttributeData>} customAttributes
 */
Type.prototype.customAttributes = undefined;

/**
 * @member {Boolean} isCollectible
 */
Type.prototype.isCollectible = undefined;

/**
 * @member {Number} metadataToken
 */
Type.prototype.metadataToken = undefined;

/**
 * @member {Boolean} isInterface
 */
Type.prototype.isInterface = undefined;

/**
 * @member {module:model/MemberTypes} memberType
 */
Type.prototype.memberType = undefined;

/**
 * @member {String} namespace
 */
Type.prototype.namespace = undefined;

/**
 * @member {String} assemblyQualifiedName
 */
Type.prototype.assemblyQualifiedName = undefined;

/**
 * @member {String} fullName
 */
Type.prototype.fullName = undefined;

/**
 * @member {module:model/Assembly} assembly
 */
Type.prototype.assembly = undefined;

/**
 * @member {module:model/Module} module
 */
Type.prototype.module = undefined;

/**
 * @member {Boolean} isNested
 */
Type.prototype.isNested = undefined;

/**
 * @member {module:model/Type} declaringType
 */
Type.prototype.declaringType = undefined;

/**
 * @member {module:model/MethodBase} declaringMethod
 */
Type.prototype.declaringMethod = undefined;

/**
 * @member {module:model/Type} reflectedType
 */
Type.prototype.reflectedType = undefined;

/**
 * @member {module:model/Type} underlyingSystemType
 */
Type.prototype.underlyingSystemType = undefined;

/**
 * @member {Boolean} isTypeDefinition
 */
Type.prototype.isTypeDefinition = undefined;

/**
 * @member {Boolean} isArray
 */
Type.prototype.isArray = undefined;

/**
 * @member {Boolean} isByRef
 */
Type.prototype.isByRef = undefined;

/**
 * @member {Boolean} isPointer
 */
Type.prototype.isPointer = undefined;

/**
 * @member {Boolean} isConstructedGenericType
 */
Type.prototype.isConstructedGenericType = undefined;

/**
 * @member {Boolean} isGenericParameter
 */
Type.prototype.isGenericParameter = undefined;

/**
 * @member {Boolean} isGenericTypeParameter
 */
Type.prototype.isGenericTypeParameter = undefined;

/**
 * @member {Boolean} isGenericMethodParameter
 */
Type.prototype.isGenericMethodParameter = undefined;

/**
 * @member {Boolean} isGenericType
 */
Type.prototype.isGenericType = undefined;

/**
 * @member {Boolean} isGenericTypeDefinition
 */
Type.prototype.isGenericTypeDefinition = undefined;

/**
 * @member {Boolean} isSZArray
 */
Type.prototype.isSZArray = undefined;

/**
 * @member {Boolean} isVariableBoundArray
 */
Type.prototype.isVariableBoundArray = undefined;

/**
 * @member {Boolean} isByRefLike
 */
Type.prototype.isByRefLike = undefined;

/**
 * @member {Boolean} isFunctionPointer
 */
Type.prototype.isFunctionPointer = undefined;

/**
 * @member {Boolean} isUnmanagedFunctionPointer
 */
Type.prototype.isUnmanagedFunctionPointer = undefined;

/**
 * @member {Boolean} hasElementType
 */
Type.prototype.hasElementType = undefined;

/**
 * @member {Array.<module:model/Type>} genericTypeArguments
 */
Type.prototype.genericTypeArguments = undefined;

/**
 * @member {Number} genericParameterPosition
 */
Type.prototype.genericParameterPosition = undefined;

/**
 * @member {module:model/GenericParameterAttributes} genericParameterAttributes
 */
Type.prototype.genericParameterAttributes = undefined;

/**
 * @member {module:model/TypeAttributes} attributes
 */
Type.prototype.attributes = undefined;

/**
 * @member {Boolean} isAbstract
 */
Type.prototype.isAbstract = undefined;

/**
 * @member {Boolean} isImport
 */
Type.prototype.isImport = undefined;

/**
 * @member {Boolean} isSealed
 */
Type.prototype.isSealed = undefined;

/**
 * @member {Boolean} isSpecialName
 */
Type.prototype.isSpecialName = undefined;

/**
 * @member {Boolean} isClass
 */
Type.prototype.isClass = undefined;

/**
 * @member {Boolean} isNestedAssembly
 */
Type.prototype.isNestedAssembly = undefined;

/**
 * @member {Boolean} isNestedFamANDAssem
 */
Type.prototype.isNestedFamANDAssem = undefined;

/**
 * @member {Boolean} isNestedFamily
 */
Type.prototype.isNestedFamily = undefined;

/**
 * @member {Boolean} isNestedFamORAssem
 */
Type.prototype.isNestedFamORAssem = undefined;

/**
 * @member {Boolean} isNestedPrivate
 */
Type.prototype.isNestedPrivate = undefined;

/**
 * @member {Boolean} isNestedPublic
 */
Type.prototype.isNestedPublic = undefined;

/**
 * @member {Boolean} isNotPublic
 */
Type.prototype.isNotPublic = undefined;

/**
 * @member {Boolean} isPublic
 */
Type.prototype.isPublic = undefined;

/**
 * @member {Boolean} isAutoLayout
 */
Type.prototype.isAutoLayout = undefined;

/**
 * @member {Boolean} isExplicitLayout
 */
Type.prototype.isExplicitLayout = undefined;

/**
 * @member {Boolean} isLayoutSequential
 */
Type.prototype.isLayoutSequential = undefined;

/**
 * @member {Boolean} isAnsiClass
 */
Type.prototype.isAnsiClass = undefined;

/**
 * @member {Boolean} isAutoClass
 */
Type.prototype.isAutoClass = undefined;

/**
 * @member {Boolean} isUnicodeClass
 */
Type.prototype.isUnicodeClass = undefined;

/**
 * @member {Boolean} isCOMObject
 */
Type.prototype.isCOMObject = undefined;

/**
 * @member {Boolean} isContextful
 */
Type.prototype.isContextful = undefined;

/**
 * @member {Boolean} isEnum
 */
Type.prototype.isEnum = undefined;

/**
 * @member {Boolean} isMarshalByRef
 */
Type.prototype.isMarshalByRef = undefined;

/**
 * @member {Boolean} isPrimitive
 */
Type.prototype.isPrimitive = undefined;

/**
 * @member {Boolean} isValueType
 */
Type.prototype.isValueType = undefined;

/**
 * @member {Boolean} isSignatureType
 */
Type.prototype.isSignatureType = undefined;

/**
 * @member {Boolean} isSecurityCritical
 */
Type.prototype.isSecurityCritical = undefined;

/**
 * @member {Boolean} isSecuritySafeCritical
 */
Type.prototype.isSecuritySafeCritical = undefined;

/**
 * @member {Boolean} isSecurityTransparent
 */
Type.prototype.isSecurityTransparent = undefined;

/**
 * @member {module:model/StructLayoutAttribute} structLayoutAttribute
 */
Type.prototype.structLayoutAttribute = undefined;

/**
 * @member {module:model/ConstructorInfo} typeInitializer
 */
Type.prototype.typeInitializer = undefined;

/**
 * @member {module:model/RuntimeTypeHandle} typeHandle
 */
Type.prototype.typeHandle = undefined;

/**
 * @member {String} guid
 */
Type.prototype.guid = undefined;

/**
 * @member {module:model/Type} baseType
 */
Type.prototype.baseType = undefined;

/**
 * @member {Boolean} isSerializable
 */
Type.prototype.isSerializable = undefined;

/**
 * @member {Boolean} containsGenericParameters
 */
Type.prototype.containsGenericParameters = undefined;

/**
 * @member {Boolean} isVisible
 */
Type.prototype.isVisible = undefined;

