/*
 * EndearingApp.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ValidationSeverity from './ValidationSeverity';

/**
 * The ValidationError model module.
 * @module model/ValidationError
 * @version 1.0
 */
export default class ValidationError {
  /**
   * Constructs a new <code>ValidationError</code>.
   * @alias module:model/ValidationError
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ValidationError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValidationError} obj Optional instance to populate.
   * @return {module:model/ValidationError} The populated <code>ValidationError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ValidationError();
      if (data.hasOwnProperty('identifier'))
        obj.identifier = ApiClient.convertToType(data['identifier'], 'String');
      if (data.hasOwnProperty('errorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['errorMessage'], 'String');
      if (data.hasOwnProperty('errorCode'))
        obj.errorCode = ApiClient.convertToType(data['errorCode'], 'String');
      if (data.hasOwnProperty('severity'))
        obj.severity = ValidationSeverity.constructFromObject(data['severity']);
    }
    return obj;
  }
}

/**
 * @member {String} identifier
 */
ValidationError.prototype.identifier = undefined;

/**
 * @member {String} errorMessage
 */
ValidationError.prototype.errorMessage = undefined;

/**
 * @member {String} errorCode
 */
ValidationError.prototype.errorCode = undefined;

/**
 * @member {module:model/ValidationSeverity} severity
 */
ValidationError.prototype.severity = undefined;

