// <auto-generated />
using System;
using EndearingApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EndearingApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241224202047_AddIsSystemFieldFlag")]
    partial class AddIsSystemFieldFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.CustomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomEntityMetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomEntity", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemField")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OptionSetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomEntityId");

                    b.HasIndex("OptionSetDefinitionId");

                    b.HasIndex("Name", "CustomEntityId")
                        .IsUnique();

                    b.ToTable("Field", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.FormMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomEntityId");

                    b.ToTable("FormMetadata", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OptionSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OptionSetId");

                    b.ToTable("Option", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.OptionSetDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OptionSetDefinition", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConstraintName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ReferencedCustomEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferencedFieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceCustomEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceFieldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReferencedCustomEntityId");

                    b.HasIndex("ReferencedFieldId");

                    b.HasIndex("SourceCustomEntityId");

                    b.HasIndex("SourceFieldId");

                    b.ToTable("Relationship", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.SystemSettingsAggregate.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("JsonSetting")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Field", b =>
                {
                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.CustomEntity", "CustomEntity")
                        .WithMany("Fields")
                        .HasForeignKey("CustomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.OptionSetDefinition", "OptionSetDefinition")
                        .WithMany()
                        .HasForeignKey("OptionSetDefinitionId");

                    b.Navigation("CustomEntity");

                    b.Navigation("OptionSetDefinition");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.FormMetadata", b =>
                {
                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.CustomEntity", "CustomEntity")
                        .WithMany()
                        .HasForeignKey("CustomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomEntity");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Option", b =>
                {
                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.OptionSetDefinition", "OptionSet")
                        .WithMany("Options")
                        .HasForeignKey("OptionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionSet");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Relationship", b =>
                {
                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.CustomEntity", "ReferencedCustomEntity")
                        .WithMany()
                        .HasForeignKey("ReferencedCustomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.Field", "ReferencedField")
                        .WithMany("ReferencedRelationshipToThis")
                        .HasForeignKey("ReferencedFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.CustomEntity", "SourceCustomEntity")
                        .WithMany("Relationships")
                        .HasForeignKey("SourceCustomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.Field", "SourceField")
                        .WithMany("SourcedRelationshipByThis")
                        .HasForeignKey("SourceFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferencedCustomEntity");

                    b.Navigation("ReferencedField");

                    b.Navigation("SourceCustomEntity");

                    b.Navigation("SourceField");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.CustomEntity", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Field", b =>
                {
                    b.Navigation("ReferencedRelationshipToThis");

                    b.Navigation("SourcedRelationshipByThis");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.OptionSetDefinition", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
