// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using EndearingApp.Infrastructure.Data;

#nullable disable

namespace EndearingApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.CustomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomEntity", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomEntityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomEntityId");

                    b.HasIndex("Name", "CustomEntityId")
                        .IsUnique();

                    b.ToTable("Field", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConstraintName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ReferencedCustomEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferencedFieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceCustomEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceFieldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReferencedCustomEntityId");

                    b.HasIndex("ReferencedFieldId");

                    b.HasIndex("SourceCustomEntityId");

                    b.HasIndex("SourceFieldId");

                    b.ToTable("Relationship", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.SystemSettings.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("JsonSetting")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting", "customization");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Field", b =>
                {
                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.CustomEntity", "CustomEntity")
                        .WithMany("Fields")
                        .HasForeignKey("CustomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomEntity");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Relationship", b =>
                {
                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.CustomEntity", "ReferencedCustomEntity")
                        .WithMany()
                        .HasForeignKey("ReferencedCustomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.Field", "ReferencedField")
                        .WithMany("ReferencedRelationshipToThis")
                        .HasForeignKey("ReferencedFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.CustomEntity", "SourceCustomEntity")
                        .WithMany("Relationships")
                        .HasForeignKey("SourceCustomEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EndearingApp.Core.CustomEntityAggregate.Field", "SourceField")
                        .WithMany("SourcedRelationshipByThis")
                        .HasForeignKey("SourceFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferencedCustomEntity");

                    b.Navigation("ReferencedField");

                    b.Navigation("SourceCustomEntity");

                    b.Navigation("SourceField");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.CustomEntity", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("EndearingApp.Core.CustomEntityAggregate.Field", b =>
                {
                    b.Navigation("ReferencedRelationshipToThis");

                    b.Navigation("SourcedRelationshipByThis");
                });
#pragma warning restore 612, 618
        }
    }
}
